### ISSUE TITLE
Using the n_of_n_taproot_public_key as the internal taproot key

### ISSUE THREAD

**Issue by OrestisAlpos** [BitVM/BitVM#150]
Why do some of the connectors, such as Connector1, use the `n_of_n_taproot_public_key` as the internal key?

I thought it could have to do with the optimization mentioned in the third bullet [here](https://github.com/bitcoin/bips/blob/master/bip-0341.mediawiki#constructing-and-spending-taproot-outputs), but this does not seem to apply here. No leaf allows this key to spend the input by itself, but always in conjunction with some some other condition(s) (e.g., a relative timelock). Therefore setting the internal key to the signers' key gives them more power than they need.

Should a nothing-up-my-sleeve key be used instead, as mentioned on the same link?

**Comment by OrestisAlpos** [comment]
Concrete examples:
- [Connector 1](https://github.com/BitVM/BitVM/blob/b6971f09b181bfd08c95cfc95a4cfb77e2efdc5e/src/bridge/connectors/connector_1.rs#L131C73-L132C1)
- [Connector 2](https://github.com/BitVM/BitVM/blob/b6971f09b181bfd08c95cfc95a4cfb77e2efdc5e/src/bridge/connectors/connector_2.rs#L100)

**Comment by lucidLuckylee** [comment]
Looks like that is used to be able to skip the light client phase for testing purposes (as the light client design is not completed yet).

> Therefore setting the internal key to the signers' key gives them more power than they need.

I don't think it does. The whole system relies on the assumption that one of the n parties delete their private key as otherwise all n parties can collude to directly spend the locked funds.

Nevertheless, you are right that we could and should use an unspendable internal key as soon as the light client is implemented (so we can mock it up another way) to make sure no one accidentally pre-signs the key spend path.
