### ISSUE TITLE
Why checking the lower bound of a digit?

### ISSUE THREAD

**Issue by SergioDemianLerner** [BitVM/BitVM#35]
The following code checks the bounds of each Winternitz digit:

https://github.com/BitVM/BitVM/blob/ce1391e14e5c58789a4a8c3a05aac7627e8615a6/src/winternitz.rs#L132

This full check doesn't seem to be required.  If the digit is negative, then OP_PICK will fail. 

Therefore the following code could be replaced:
```
OP_DUP
 0
 { D + 1 }
 OP_WITHIN 
 OP_VERIFY
```
by
```
 OP_DUP
 { D + 1 }
 OP_LESSTHAN
 OP_VERIFY
```
If we don't care about digit uniqueness, we can reduce the size further and just limit it to D:
```
 { D }
 OP_MIN
```

3 opcodes are saved.
Am I missing something?

**Comment by RobinLinus** [comment]
Thank you very much, that's a great improvement! `{D} OP_MIN` seems to do the job indeed. Now we're close to 29 bytes of signature per message bit. Credited you in the comments!

Drawback: The unlocking script becomes malleable. An attacker can might try fee-pinning attacks by changing the size of each digit to 4 bytes instead of 1 byte. The attacker can't use larger digits than 32 bit because `OP_MIN` would fail.

Not sure though if this bug is actually exploitable.
